// Generated by https://quicktype.io

export interface Meal {
    strMeal:      string;
    strMealThumb: string;
    idMeal:       string;
}
// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface Category {
    idCategory:             string;
    strCategory:            string;
    strCategoryThumb:       string;
    strCategoryDescription: string;
}
